name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lokeshb003/calendar-app-mongodb:latest
    - name: login to DockerHub
      run: docker login -u lokeshb003 -p kepler22b
    - name: push to dockerhub
      run: docker push lokeshb003/calendar-app-mongodb:latest
